package com.andrei1058.bedwars.api.arena;

public enum NextEvent {
    DIAMOND_GENERATOR_TIER_II, DIAMOND_GENERATOR_TIER_III, EMERALD_GENERATOR_TIER_II, EMERALD_GENERATOR_TIER_III, BEDS_DESTROY, ENDER_DRAGON, GAME_END;
}
