name: RankubBedWars
api-version: '1.13'
version: ${project.version}
authors: [andrei1058, forked by _MegArthur]
description: BedWars minigame by andrei1058. Fork by _MegArthur
main: com.andrei1058.bedwars.BedWars
softdepend: [Vault,PlaceholderAPI,Citizens,Parties,SlimeWorldManager,VipFeatures,Enhanced-SlimeWorldManager,PartyAndFriends,Spigot-Party-API-PAF]
#load: STARTUP
